### ISSUE TITLE
S3 configuration: request for help

### ISSUE THREAD

**Issue by Antiarchitect** [eclipse/hawkbit-extensions#54]
Hi, @schabdo seems like I need your help again. I'm trying to test the S3 extension first against true AWS S3 and MinIO later. Currently, I have application-custom.properties:

```
org.eclipse.hawkbit.artifact.repository.s3.enabled=true
org.eclipse.hawkbit.artifact.repository.s3.bucketName=my-bucket-name
aws.region=eu-central-1
aws.s3.endpoint=s3.eu-central-1.amazonaws.com
aws.accessKeyId=xxxxxxxxxxx
aws.secretAccessKey=xxxxxxxxxxxxxxxxx
```

I'm testing via GUI - Uploads section. Seems like artifacts are not using S3 storage at all. Is my configuration correct?

**Comment by Antiarchitect** [comment]
As I'm using the edge of hawkbit the dependency configuration in hawkbit-runtime/hawkbit-update-server/pom.xml
```
      <dependency>
          <groupId>org.eclipse.hawkbit</groupId>
          <artifactId>hawkbit-extension-artifact-repository-s3</artifactId>
          <version>${project.version}</version>
          <scope>system</scope>
          <systemPath>${project.basedir}/src/main/resources/hawkbit-extension-artifact-repository-s3.jar</systemPath>
      </dependency>
```

**Comment by Antiarchitect** [comment]
I've reviewed the code of this extension and it seems bucketName should be set via `org.eclipse.hawkbit.repository.s3.bucketName=my-bucket-name` (without artifact). Configuration namespaces for bucketName and enabled do not match - it's a bit confusing.

**Comment by schabdo** [comment]
Have you enabled the S3 extension via property `org.eclipse.hawkbit.artifact.repository.s3.enabled=true`  ? Otherwise local file storage will still be the default

**Comment by schabdo** [comment]
> bucketName should be set

Exactly. And I don't think you need `aws.s3.endpoint` set. This should be handled by the AWS SDK automatically

**Comment by Antiarchitect** [comment]
Setting org.eclipse.hawkbit.repository.s3.bucketName=my-bucket-name has no success.
is "--spring.profiles.active=custom" enough in Dockerfile ENTRYPOINT?

**Comment by schabdo** [comment]
This should do the trick:
```
ENTRYPOINT ["java","-Dspring.profiles.active=custom","-jar", ....
```
You can easily verify the activated profile in the console output by searching for this line:
```
INFO 1 --- [ main] org.eclipse.hawkbit.app.Start : The following profiles are active: custom
```

**Comment by Antiarchitect** [comment]
I see that profile is active - confirmed. I'm not sure if artifact-repository-s3 is enabled and I've set configuration properly.

**Comment by schabdo** [comment]
Just enable Spring Boot's debug mode via property `-Ddebug=true`(cf. [logging to console](https://docs.spring.io/autorepo/docs/spring-boot/current/reference/html/spring-boot-features.html#boot-features-logging-console-output)) and you'll get all kinds of output. The one which is of interest is whether or not the `S3RepositoryAutoConfiguration` is loaded by Spring or not

**Comment by Antiarchitect** [comment]
Seems like negative - nothing similar in logs.

```
org.eclipse.hawkbit.artifact.repository.s3.enabled=true
org.eclipse.hawkbit.repository.s3.bucketName=enapter-hawkbit
```
Are these correct settings?

**Comment by Antiarchitect** [comment]
My Dockerfile is multistaged:

```
FROM maven:3.6.3-jdk-8-openj9 AS artifact-repository-s3

RUN set -x \
    && apt-get update \
    && apt-get install -y git \
    && apt-get clean -y
RUN set -x \
    && git clone https://github.com/eclipse/hawkbit-extensions.git /build \
    && cd /build \
    && git reset --hard 22a4c60a1072327179bbf1dcd4e65086895e55a0
RUN set -x \
    && cd /build/hawkbit-extension-artifact-repository-s3 \
    && mvn clean install -DskipTests

FROM maven:3.6.3-jdk-8-openj9 AS hawkbit

RUN set -x \
    && apt-get update \
    && apt-get install -y git \
    && apt-get clean -y
RUN set -x \
    && git clone https://github.com/Enapter/hawkbit.git /build \
    && cd /build \
    && git reset --hard d16c73f5406606167115934ba2a0fd511c763ef7

COPY --from=artifact-repository-s3 /build/hawkbit-extension-artifact-repository-s3/target/hawkbit-extension-artifact-repository-s3-0.3.0-SNAPSHOT.jar "/build/hawkbit-runtime/hawkbit-update-server/src/main/resources/hawkbit-extension-artifact-repository-s3.jar"

COPY ./application-enapter.properties /build/hawkbit-runtime/hawkbit-update-server/src/main/resources/

RUN set -x \
    && cd /build \
    && mvn clean install -DskipTests

FROM openjdk:8u242-jre-slim

ENV HAWKBIT_HOME=/opt/hawkbit

EXPOSE 8080

COPY --from=hawkbit /build/hawkbit-runtime/hawkbit-update-server/target/hawkbit-update-server-0.3.0-SNAPSHOT.jar "${HAWKBIT_HOME}/hawkbit-update-server.jar"

VOLUME "${HAWKBIT_HOME}/data"

WORKDIR $HAWKBIT_HOME

ENTRYPOINT ["java","-jar","hawkbit-update-server.jar","--debug", "--spring.profiles.active=enapter", "-Xms768m -Xmx768m -XX:MaxMetaspaceSize=250m -XX:MetaspaceSize=250m -Xss300K -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError"]
```
Am I doing build correctly?

**Comment by Antiarchitect** [comment]
@schabdo Should the dependencies be set in general hawkbit pom.xml file or just inside the hawkbit-update-server

**Comment by Antiarchitect** [comment]
Now I'm here:

```
[36mhawkbit_1     |[0m java.lang.IllegalStateException: Error processing condition on org.eclipse.hawkbit.artifact.repository.S3RepositoryAutoConfiguration.awsCredentialsProvider
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
[36mhawkbit_1     |[0m 	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
[36mhawkbit_1     |[0m 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:181)
[36mhawkbit_1     |[0m 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141)
[36mhawkbit_1     |[0m 	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
[36mhawkbit_1     |[0m 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
[36mhawkbit_1     |[0m 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
[36mhawkbit_1     |[0m 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
[36mhawkbit_1     |[0m 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
[36mhawkbit_1     |[0m 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
[36mhawkbit_1     |[0m 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
[36mhawkbit_1     |[0m 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
[36mhawkbit_1     |[0m 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
[36mhawkbit_1     |[0m 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
[36mhawkbit_1     |[0m 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
[36mhawkbit_1     |[0m 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
[36mhawkbit_1     |[0m 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
[36mhawkbit_1     |[0m 	at org.eclipse.hawkbit.app.Start.main(Start.java:35)
[36mhawkbit_1     |[0m 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[36mhawkbit_1     |[0m 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[36mhawkbit_1     |[0m 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[36mhawkbit_1     |[0m 	at java.lang.reflect.Method.invoke(Method.java:498)
[36mhawkbit_1     |[0m 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
[36mhawkbit_1     |[0m 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
[36mhawkbit_1     |[0m 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
[36mhawkbit_1     |[0m 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
[36mhawkbit_1     |[0m Caused by: java.lang.IllegalStateException: @ConditionalOnMissingBean did not specify a bean using type, name or annotation and the attempt to deduce the bean's type failed
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.validate(OnBeanCondition.java:451)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:441)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:416)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:158)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
[36mhawkbit_1     |[0m 	... 25 common frames omitted
[36mhawkbit_1     |[0m Caused by: org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanTypeDeductionException: Failed to deduce bean type for org.eclipse.hawkbit.artifact.repository.S3RepositoryAutoConfiguration.awsCredentialsProvider
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanTypeForBeanMethod(OnBeanCondition.java:496)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanType(OnBeanCondition.java:483)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.<init>(OnBeanCondition.java:435)
[36mhawkbit_1     |[0m 	... 28 common frames omitted
[36mhawkbit_1     |[0m Caused by: java.lang.ClassNotFoundException: com.amazonaws.auth.AWSCredentialsProvider
[36mhawkbit_1     |[0m 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[36mhawkbit_1     |[0m 	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[36mhawkbit_1     |[0m 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
[36mhawkbit_1     |[0m 	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[36mhawkbit_1     |[0m 	at java.lang.Class.forName0(Native Method)
[36mhawkbit_1     |[0m 	at java.lang.Class.forName(Class.java:348)
[36mhawkbit_1     |[0m 	at org.springframework.util.ClassUtils.forName(ClassUtils.java:275)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.getReturnType(OnBeanCondition.java:505)
[36mhawkbit_1     |[0m 	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanSearchSpec.addDeducedBeanTypeForBeanMethod(OnBeanCondition.java:491)
[36mhawkbit_1     |[0m 	... 30 common frames omitted
[36mhawkbit_1     |[0m 
```

**Comment by schabdo** [comment]
Interesting, I never tried to build S3 extension separately and copy the artefact later on straight into the `hawkbit-update-server`. 

> Should the dependencies be set in general hawkbit pom.xml file or just inside the hawkbit-update-server

Exactly, that's the way I do it. Just add the maven dependency to the `hawkbit-update-server` pom.xml so as soon as you build the `hawkbit-update-server` Maven will do all the transitive dependency resolution for you and you shouldn't get `ClassNotFoundException` due to missing AWS SDK on the classpath

**Comment by schabdo** [comment]
@thmai11 may I ask you for help? Maybe you already have something similar up and running in a single `Dockerfile`. That would be awesome!

**Comment by thmai11** [comment]
Hello, You may take a look at my multi-stage docker file here : https://github.com/thmai11/hawkbit-s3-backend/blob/master/Dockerfile. Also check the read me for more detailed explanation. I don't see any problem building the extension in a separate stage but I don't see it added as a dependencies to hawkbit via the pom.xml which might be the issue? My docker is also available here: https://hub.docker.com/u/drgnzn Let me know if I can be of any help!

**Comment by Antiarchitect** [comment]
@schabdo @thmai11 Now I see. Thank you, guys. Will try when I have time for this.

**Comment by Antiarchitect** [comment]
Current error:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amazonaws.services.s3.AmazonS3]: Factory method 'amazonS3' threw exception; nested exception is java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
```

**Comment by thmai11** [comment]
`Only one of Region or EndpointConfiguration may be set.` Could you provide us the argument you send to hawkbit server when you launch it?

**Comment by Antiarchitect** [comment]
> `Only one of Region or EndpointConfiguration may be set.` Could you provide us the argument you send to hawkbit server when you launch it?

Wait a bit - if I can fix it by myself I will create a PR

**Comment by Antiarchitect** [comment]
Here it goes: https://github.com/eclipse/hawkbit-extensions/pull/55
